// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const increment: typeof autoImports.increment
  const decrement: typeof autoImports.decrement
  const reset: typeof autoImports.reset
  const count: typeof autoImports.count
  const loadStores: typeof autoImports.loadStores
  const loadCatalog: typeof autoImports.loadCatalog
  const loadSpecials: typeof autoImports.loadSpecials
  const loadSiteModel: typeof autoImports.loadSiteModel
  const loadProductReviews: typeof autoImports.loadProductReviews
  const money: typeof autoImports.money
  const telHref: typeof autoImports.telHref
  const potency: typeof autoImports.potency
  const potencyLabel: typeof autoImports.potencyLabel
  const resolveStoreSlug: typeof autoImports.resolveStoreSlug
  const emptyProductReviews: typeof autoImports.emptyProductReviews
  const STORE_COOKIE: typeof autoImports.STORE_COOKIE
  const activeRates: typeof autoImports.activeRates
  const totalsFor: typeof autoImports.totalsFor
  const blendedRate: typeof autoImports.blendedRate
  const looksLikeMmic: typeof autoImports.looksLikeMmic
  const cardIsValidOn: typeof autoImports.cardIsValidOn
  const totalsFrom: typeof autoImports.totalsFrom
}

export {}
