// Generated by bun-plugin-auto-imports

// This file injects auto-imported functions into the global scope
// Import this file early in your application startup

import * as autoImports from './index'

// Inject into globalThis for runtime access
Object.assign(globalThis, autoImports)

// TypeScript declarations
declare global {
  const increment: typeof autoImports.increment
  const decrement: typeof autoImports.decrement
  const reset: typeof autoImports.reset
  const count: typeof autoImports.count
  const loadStores: typeof autoImports.loadStores
  const loadCatalog: typeof autoImports.loadCatalog
  const loadSpecials: typeof autoImports.loadSpecials
  const loadSiteModel: typeof autoImports.loadSiteModel
  const loadProductReviews: typeof autoImports.loadProductReviews
  const money: typeof autoImports.money
  const telHref: typeof autoImports.telHref
  const potency: typeof autoImports.potency
  const emptyProductReviews: typeof autoImports.emptyProductReviews
}

export {}
