-- @generated by `buddy migrate:regenerate` — edits will be overwritten
ALTER TABLE "orders" ADD COLUMN "store_slug" TEXT default '';
ALTER TABLE "orders" ADD COLUMN "is_medical" INTEGER default 0;
ALTER TABLE "orders" ADD COLUMN "mmic_number" TEXT default '';
ALTER TABLE "orders" ADD COLUMN "mmic_expires_at" TEXT default '';
ALTER TABLE "orders" ADD COLUMN "exempted_tax_amount" INTEGER default 0;
ALTER TABLE "orders" ADD COLUMN "store_id" INTEGER REFERENCES "stores"("id");
