-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "inquiries" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "kind" TEXT not null default 'contact',
  "name" TEXT not null,
  "email" TEXT not null,
  "phone" TEXT default '',
  "subject" TEXT default '',
  "message" TEXT default '',
  "details" TEXT default '{}',
  "status" TEXT default 'new',
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "inquiries_uuid_unique" ON "inquiries" ("uuid");
