-- @generated by `buddy migrate:regenerate` — edits will be overwritten
CREATE TABLE IF NOT EXISTS "store_products" (
  "id" INTEGER PRIMARY KEY AUTOINCREMENT,
  "price" INTEGER not null,
  "compare_at_price" INTEGER default 0,
  "unit_size" TEXT default '',
  "is_available" INTEGER default 1,
  "stock_count" INTEGER default -1,
  "fulfillment" TEXT CHECK ("fulfillment" IN ('pickup', 'delivery', 'both', 'none')) default 'both',
  "source_id" TEXT default '',
  "synced_at" TEXT,
  "store_id" INTEGER REFERENCES "stores"("id"),
  "product_id" INTEGER REFERENCES "products"("id"),
  "created_at" TEXT not null default CURRENT_TIMESTAMP,
  "updated_at" TEXT,
  "uuid" TEXT
);
CREATE UNIQUE INDEX IF NOT EXISTS "store_products_uuid_unique" ON "store_products" ("uuid");
